Update changeLog for V3.0.1
admin-shell-io/aas-specs pull request #367
Opened 2024-02-29 17:20 UTC by BirgitBoss

Some changes already prepared for V3.1 were now moved to the bugfix version V3.0.1

2024-02-29 17:36 UTC, BirgitBoss commented
@j-blume: may you please also review this PR after reviewing V3.0.1? Thank you

2024-03-01 18:07 UTC, J-Blume requested changes

2024-03-01 18:07 UTC, J-Blume approved these changes

2024-03-04 17:16 UTC, BirgitBoss commented on documentation/IDTA-01001/modules/ROOT/pages/IDTA-01001_ChangeLog.adoc
> +* Change PathType: support complete URI scheme for files RFC2396/RFC2732 conformant to anyURI of XML Schema 1.0  (https://github.com/admin-shell-io/aas-specs/issues/299[#299])
```suggestion
* Change PathType: support complete URI scheme for files RFC2396 conformant to anyURI of XML Schema 1.0 , Part 2 (https://github.com/admin-shell-io/aas-specs/issues/299[#299])
```

2024-03-04 17:18 UTC, merged