adjust the names of classes and attribbutes to get consistent pattern of serialization
admin-shell-io/aas-specs pull request #41
Opened 2021-07-21 11:58 UTC by changqin26

2021-07-21 12:01 UTC, changqin26 commented
The first adjustment is to remove the "Refs/Ref" suffix of the name of classes like submodel, conceptDescription etc.

2021-07-21 12:06 UTC, changqin26 commented
The second proposal would be that we name all properties in the singular form. Because some properties can only be in the singular form and to achieve consistencies, all other properties are also in the singular form. 

**The properties, which can only be in the singular form.**
ConceptDescription/**isCaseOf** | Reference | 0..*
Formula/**dependsOn** | Reference | 0..*
AssetAdministrationShell/**derivedFrom** | AssetAdministrationShell/derivedForm | 0..1
Extension/**refersTo** | Reference | 0..1
BasicEvent/**observed** | Referable | 1
SubmodelElementCollection/**ordered** | boolean | 0..1

2021-07-21 12:09 UTC, changqin26 commented
@mristin @JoergWende Could you please take a look at the proposals here and express your opinions?

2021-07-21 12:37 UTC, changqin26 commented
For the second point,  conceptDescription/isCaseOf and Formula/dependsOn are elements with unlimited cardinality, however, it is almost not possible to express "isCaseOf" and "dependsOn" in plural's, right?

2021-07-21 13:10 UTC, JoergWende commented
ok ... what is the question ... or the proposal ?
![image](https://user-images.githubusercontent.com/47781385/126493714-331c4527-d620-4e63-87df-f1388d99411d.png)

If I remember right - we had _references_ in the past but removed them

2021-12-22 21:37 UTC, BirgitBoss requested changes
I think there is a misunderstanding of the concept of "<Referable>Refs_t and <Referable>Ref_t (like SubmodelRefs_t and SubmodelRef_t) in contrast to <Referable>_ t and <Referable>s_t (Submodel_t and Submodels_t). I think the xml serialization is correct like it is. So PR not approved or please explain which of the serialization rules for XML is not followed by the current XML serialization.

2021-12-22 21:37 UTC, BirgitBoss commented on schemas/xml/AAS.xsd
> +			<element maxOccurs="unbounded" minOccurs="0" name="submodel" type="aas:submodel_t"/>
submodelRefs_t is correct, it is a shared aggregation and shared aggregation are always serialized as reference. But perhaps maxOccurs needs to be "1"

2021-12-22 21:37 UTC, BirgitBoss commented on schemas/xml/AAS.xsd
> +			<element maxOccurs="unbounded" minOccurs="0" name="billOfMaterials" type="aas:submodel_t"/>
submodelRefs_t is correct
But perhaps maxOccurs needs to be "1"

2021-12-22 21:37 UTC, BirgitBoss commented on schemas/xml/AAS.xsd
> +	<complexType name="conceptDescription_t">
conceptDescription_t would be a completely different type than conceptDescriptionRefs. Probably both are needed or one can be removed completly.

2022-01-03 09:57 UTC, changqin26 commented
Thanks for your explanation, we can close this PR.

2022-01-03 09:57 UTC, closed without merging