Replace xs:dateType with xs:dateTime
admin-shell-io/aas-specs pull request #461
Opened 2024-08-01 15:47 UTC by sebbader-sap

xs:dateType does not exist, neither in XML Schema 1.0 or 1.1.
Furthermore, XML Schema Datatypes 1.1 also know the xs:dateTime, therefore, there is no need to switch to xs:dateTimeStamp.

closes #467

2024-08-01 15:48 UTC, sebbader-sap commented
I have no clue why Github thinks that I am also adding the image55.png with this PR...

2024-09-06 19:10 UTC, BirgitBoss commented on documentation/IDTA-01001/modules/ROOT/pages/spec-metamodel/datatypes.adoc
> +"2000-01-01T14:23:00.66372+14:00"footnote:[Corresponds to https://www.w3.org/TR/xmlschema11-2/#dateTime[xs:dateTime] in XML Schema 1.1]
```suggestion
"2000-01-01T14:23:00.66372+14:00"footnote:[Corresponds to https://www.w3.org/TR/xmlschema-2/#dateTime[xs:dateTime] in XML Schema 1.0]
```

2024-09-06 19:11 UTC, BirgitBoss requested changes
Thanks, this is a bug. I corrected the footnote, we use schema 1.0, not schema 1.1

2024-12-12 15:02 UTC, BirgitBoss approved these changes

2024-12-12 15:02 UTC, merged